### ISSUE TITLE
Модалка из модалки

### ISSUE THREAD

**Issue by khomuk** [maxdenaro/gulp-maxgraph#11]
Привет!
Как я понял модалку из модалки вызвать не получится в текущей сборке.
Возможна вообще доработка такая?

**Comment by maxdenaro** [comment]
Привет, в плагине graph-modal возможно вызвать модалку из модалки, при этом предыдущая закрывается) Пример есть по-моему в документации плагина как раз

**Comment by khomuk** [comment]
Разобрался, спасибо огромное!
