### ISSUE TITLE
как найти плагин projects snippets?

### ISSUE THREAD

**Issue by RKarseka** [maxdenaro/gulp-maxgraph#13]
> Рекомендуемые плагины для VS Code

> Самый важный из них – projects snippets

добавь ссылочку, пожалуйста. не для ленивых, вот без пол литра не понять, что хотел сказать автор. 
![image](https://user-images.githubusercontent.com/5398066/156498167-04f05cc7-058c-4f87-9b56-6f46d4b1719b.png)

**Comment by maxdenaro** [comment]
Так VS Code сам его предложит да и все :)

**Comment by RKarseka** [comment]
а почему мне не предложил?

**Comment by roman-ier** [comment]
а почему мне не предложил?

**Comment by Makkons** [comment]
> а почему мне не предложил?

Проверьте в корне проекта наличие папки ".vscode", там должен лежать файл "extensions.json".
Если он есть, то vscode должен был предложить установку всех необходимых плагинов, которые рекомендует автор.
Если что-то пошло не так, вы можете также найти данный файл в этом репозитории и посмотреть список всех необходимых плагинов, которые можно поставить вручную.
