### ISSUE TITLE
_functions.js ошибка подключения enable-scroll

### ISSUE THREAD

**Issue by Makkons** [maxdenaro/gulp-maxgraph#14]
Не уверен что ошибка стоит создания целого issue, но в подключении модуля enable-scroll есть опечатка.

`// import { enableScroll } from './functions/disable-scroll';`

заменить на:
`// import { enableScroll } from './functions/enable-scroll';`

Если ошибка слишком незначительна для указания, поправьте меня и я буду в следующий раз вести себя скромнее.

**Comment by Makkons** [comment]
Сразу добавлю: в readme.md указано что для фиксированных элементов при использовании disableScroll и enableScroll необходимо добавить класс **fix-block**, но в функциях работа идет с классом **fixed-block**.
Наверно необходимо исправить опечатку в readme.

**Comment by maxdenaro** [comment]
Точно, опечатки бывают..)) спасибо, поправлю
