### ISSUE TITLE
вирус

### ISSUE THREAD

**Issue by kross23** [maxdenaro/gulp-maxgraph#20]
в сборке в файле "_postinstall.js"  обнаружен троян JS.Siggen5.44590.
вот что пишет антивирус : 
"Объект";"Угроза";"Действие";"Путь";
"_postinstall.js";"JS.Siggen5.44590";"Перемещено";"C:\Users\javaScript\верстка\gulp-maxgraph\node_modules\es5-ext\_postinstall.js";

**Comment by maxdenaro** [comment]
Ну увы, тут я ничего не поделаю) вероятно, надо писать авторам этого пакета.
