### ISSUE TITLE
HTMLMinify - выбрасывает <span>sometext</span> из структуры

### ISSUE THREAD

**Issue by desgleb** [maxdenaro/gulp-maxgraph#21]
Максим, добрый день.

Заметил, что при сборке gulp build, где используется функция HTMLMinify, происходит выброс тега `<span>` с содержимым из тега `<a>`. А также выбрасывает `<svg><use>` из тега `<a>`.

`<ul class="list-reset market__header-sort market-sort">
            <li class="market-sort__item">
              <a
              href="javascript:void(0);"
              class="btn btn-reset btn-transparent market-sort__btn active"
              >
            </li>
              <span>по цене</span>
              <svg class="sort-triangle">
                <use xlink:href="img/sprite.svg#sort-triangle"></use>
              </svg>
            </a>
            <li class="market-sort__item">
              <a
              href="javascript:void(0);"
              class="btn btn-reset btn-transparent market-sort__btn"
              >
            </li>
              <span>по рейтингу</span>
              <svg class="sort-triangle">
                <use xlink:href="img/sprite.svg#sort-triangle"></use>
              </svg>
            </a>
            <li class="market-sort__item">
              <a
              href="javascript:void(0);"
              class="btn btn-reset btn-transparent market-sort__btn"
              >
            </li>
              <span>по скорости выполнения</span>
              <svg class="sort-triangle">
                <use xlink:href="img/sprite.svg#sort-triangle"></use>
              </svg>
            </a>
          </ul>`

**Comment by maxdenaro** [comment]
Добрый день!
Это уже сломанный код, или исходный?
Если сломанный - нужен исходный.

**Comment by desgleb** [comment]
Это был исходный код, в котором я сам сделал ошибку, видимо случайно перенес закрывающий тег `</li>`. Сейчас попробовал с уже правильной разметкой. Все работает штатно!

Спасибо и извини за необоснованное беспокойство.

**Comment by maxdenaro** [comment]
Бывает))
