### ISSUE TITLE
Проблема с стилей

### ISSUE THREAD

**Issue by Fillinn** [maxdenaro/gulp-maxgraph#29]
**Здравствуйте, Максим Васянович!**
Я впервые использую ваша сборка GULP.
Мне очень понравится ваша сборка. я смотрел ютуб твой канал видео про инструкция  сборка GULP.
Но у меня пришли проблема сборку стиль. Не возможно локальные файлы в scss vendor.
Я все соблюдал порядок подключения.
как решить эту проблему?
Покажу образ ошибку (фото), здесь
https://ibb.co/dfVsr12
https://ibb.co/t361Ytd
https://ibb.co/6XKJmgT
https://ibb.co/pP7djRt
(сайт надежный) https://ru.imgbb.com/
Спасибо большое!

**Comment by maxdenaro** [comment]
Добрый день. Попробуйте скачать эту библиотеку через npm и оттуда взять файл стилей. Думаю, в этом косяк.
