### ISSUE TITLE
Разделение js файлов

### ISSUE THREAD

**Issue by andreypo22** [maxdenaro/gulp-maxgraph#30]
Максим, добрый день!
При верстке многостраничного сайта предпочтительнее подключение скриптов отдельно для каждой страницы html, чтобы использовать только необходимые для этой страницы подключения. Но js компоненты компилируются в один файл main.js
Возможно ли реализовать отдельное подключение?

**Comment by denis88k** [comment]
самый простой вариант создать несколько main.js файлов и импортировать в него необходимые для страницы js файлы. а в файле gulpfile продублировать логику работы
а вообще модульность/ компонентность лучше всего работает в webpack. так что если прям очень хочется, то поизучай webpack, но это смотря что от тебя будет требовать твой заказчик или работодатель)
