### ISSUE TITLE
"npm i " выдает ошибку с установкой phantomjs-prebuilt@2.1.16

### ISSUE THREAD

**Issue by mottodor** [maxdenaro/gulp-maxgraph#32]
[2023-07-18T13_45_43_772Z-debug-0.log](https://github.com/maxdenaro/gulp-maxgraph/files/12081221/2023-07-18T13_45_43_772Z-debug-0.log)

После клонирования и "npm i " выдает ошибку с установкой phantomjs-prebuilt@2.1.16

**Comment by maxdenaro** [comment]
А что с версией ноды?

**Comment by mottodor** [comment]
пробовал через 16.20.1 и 18.16.1

**Comment by mottodor** [comment]
помогла установка bzip2
