### ISSUE TITLE
Ошибки при nmp run build

### ISSUE THREAD

**Issue by Dikht** [maxdenaro/gulp-maxgraph#37]
src/scss/mixins/_layout.scss
  18:24  ✖  Expected map.get instead of map-get  scss/no-global-function-names
  23:24  ✖  Expected map.get instead of map-get  scss/no-global-function-names

✖ 2 problems (2 errors, 0 warnings)

**Comment by maxdenaro** [comment]
Добрый день! Залил фикс, должно быть все в порядке) спасибо!

**Comment by Dikht** [comment]
Никак не хочет делать билд. Проект пустой, после установки пакетов ничего не менялось и не добавлялось.

`$ npm run build

> gulp-builder@3.0.0 build
> npm run stylelint && npm run code && gulp build --build


> gulp-builder@3.0.0 stylelint
> npx stylelint **/*.scss


> gulp-builder@3.0.0 code
> editorconfig-checker

.ecrc:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.editorconfig:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.gitignore:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.htmlhintrc:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.stylelintignore:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.vscode/extensions.json:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.vscode/snippets/html.json:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/config/paths.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/cache.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/clean.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/html-include.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/html-minify.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/images.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/resources.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/rewrite.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/scripts-backend.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/scripts.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/sprite.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/styles-backend.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/styles.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/webp.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/zip.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/index.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/_components.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/_functions.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/_vars.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/components/ex.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/burger.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/check-viewport.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/disable-scroll.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/enable-scroll.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/fix-fullheight.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/header-height.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/mobile-check.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/throttle.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/validate-forms.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/main.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/partials/footer.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/partials/head.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/partials/header.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/_fonts.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/_mixins.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/_settings.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/_vars.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/components/_header.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/main.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_breakpoint.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_burger.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_checkbox.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_disable-mob-hover.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_flex.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_font-face.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_layout.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_mini.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_tabs.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character

110 errors found`

**Comment by maxdenaro** [comment]
В закрытом ишью писать уже не надо)
Судя по ошибкам, в вашей системе возможно другой символ конца строки, lf вместо crlf или наоборот.
Можно попробовать исправить это с помощью плагина prettier. Ну или вручную каждый файл

**Comment by Dikht** [comment]
Спасибо!
Не хотел плодить тикеты ))

пн, 27 мая 2024 г., 17:36 Maksim Vasyanovich ***@***.***>:
