### ISSUE TITLE
Не инициализируется карта Яндекса

### ISSUE THREAD

**Issue by Artem-Golovchansky** [maxdenaro/gulp-maxgraph#38]
При выполнении задания SKILLBOX по совету куратора использую Вашу сборку.

Всё пока работает, быстро обновляются изменения.  Однако при работе с картами возникла проблема. 
Согласно инструкции я сделал:

1. Отдельный файл в **components** map.js
2. В **_components.js** прописываю импорт **import './components/map';**
3. В **head.html** прописываю  <script src="https://api-maps.yandex.ru/2.1?apikey=()&lang=ru_RU"></script> с ключом yandex api.
4. В консоли ошибок нет.

В связи с этим, мне кажется, что что-то куда-то ещё нужно прописать, чтобы карта появилась.

В собственной сборке карта работает и даже без api ключа. Поэтому не могу понять почему этого не происходит в данном случае. 
![image](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/a21e0396-5b99-445c-ab09-e7dc17bf282a)

**Comment by maxdenaro** [comment]
Здравствуйте.
Попробуйте прописать атрибут defer или подключить скрипт карты в самом низу страницы. И точно там же, внизу, прописать сам код инициализации, прямо в теге <script>.

**Comment by Artem-Golovchansky** [comment]
Все варианты перепробовал. Не инициализируется карта. Консоль по-прежнему ошибок не отражает. Только появляется это предупреждение 
![image](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/6dd95a23-7fd8-4476-8683-21195949b645)


В "кабинете разработчика" в статистике считаются мои обновления карты на странице. Т.е. api работает. Но карты нет

Не прописываются ли какие-то атрибуты тут: 
![image](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/1d445102-918f-4a94-873b-910efdc5f729)

**Comment by maxdenaro** [comment]
Я сам пробовал в теге script, все работает. Видимо, вы где-то допустили ошибку

**Comment by Artem-Golovchansky** [comment]
Здравствуйте, прописал код в теге, внизу страницы. Всё заработало, когда прописал тип script. Благодарю за ответы. Вопрос закрыт. 

Немного только жаль, что не получается написать код этого скрипта отдельно, как и другие элементы.

**Comment by maxdenaro** [comment]
Может, и есть еще какой-то вариант) но я пока нашел такой, самый простой

**Comment by Artem-Golovchansky** [comment]
Здравствуйте, Максим.

Не стану писать в GitHub. Или стоит там?

Продолжая работу с Вашей сборкой так и не смог подключить другие js
компоненты.

*Если я их прописываю в теге внизу страницы, как и код с картой яндекса -
код работает.*
Если пишу в компонентах, как в Вашем уроке - код не работает. Может там я
что-то я упускаю?


Сам код - поиска.
[image: image.png]

Это папки с файлами:
[image: image.png]

Это пропись импортов:

[image: image.png]

Буду весьма благодарен Вам за ответ.


вс, 2 июн. 2024 г. в 11:58, Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Добрый день. Видимо ваши изображения не приложились) не вижу, что там в коде

**Comment by Artem-Golovchansky** [comment]
[image: Код js.png][image: Папки с файлами проекта.png][image: Пропись
импортов.png]

вс, 9 июн. 2024 г. в 12:40, Maksim Vasyanovich ***@***.***>:

**Comment by maxdenaro** [comment]
Я не вижу ваши изображения(
Создавайте новый ишью, может там будет показывать.
