### ISSUE TITLE
Проблема с подключением скрипта. 

### ISSUE THREAD

**Issue by Artem-Golovchansky** [maxdenaro/gulp-maxgraph#39]
Здравствуйте, подключил карту яндекса внизу страницы, как и посоветовали в предыдущей теме. Возникла проблема с подключением и других частей кода. Код работает. Когда я его прописал в тегах внизу страницы - они свою работу выполняют. 

Все действия повторял за Вами из этого урока: https://rutube.ru/video/06997803df3fdf02f4dec6e7500b5f6c/

Вот что получается у меня: 
![Код js](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/d41c548e-a97e-49de-bbd6-45302c32cf86)
![Папки с файлами проекта](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/2fff6b67-b311-4127-8d4d-bc73e09f3adb)
![Пропись импортов](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/fa704ab5-7f18-4e46-84df-bf1a4ea6420f)

Что я упускаю?

**Comment by maxdenaro** [comment]
Добрый вечер. А проблема-то какая? Ошибки? Какие?

**Comment by maxdenaro** [comment]
Ну и смотрите в текущую сборку, она же обновляется. Если у вас новая версия, то  теперь надо указывать расширение файла при подключении.

import './_components.js';

**Comment by Artem-Golovchansky** [comment]
Значит я всё верно выполнял? Я пробовал прописывать расширение импортируемым файлам. Но и в этом случае код почему-то не работал на странице. Пробовал alert вызывать - не появляется. Его как-будто не видно. 

Куратор посетовал на мое написание кода внизу страницы, записал импорт в файле main.js и код сработал.

**Comment by Artem-Golovchansky** [comment]
> Добрый вечер. А проблема-то какая? Ошибки? Какие?

Ошибок никаких. Консоль чистая.

**Comment by maxdenaro** [comment]
Я не могу сказать точно, я же не вижу полной картины) нужно смотреть на весь код, если нет ошибок, но не работает - как будто бы где-то просто не подключен нужный файл

**Comment by Artem-Golovchansky** [comment]
> Я не могу сказать точно, я же не вижу полной картины) нужно смотреть на весь код, если нет ошибок, но не работает - как будто бы где-то просто не подключен нужный файл

По совету куратора вписал импорты в main.js, в том числе и скрипт яндекс карты и всё заработало, без необходимости прописывать в теге внизу страницы.
