### ISSUE TITLE
Error: Module not found

### ISSUE THREAD

**Issue by sobchak-77** [maxdenaro/gulp-maxgraph#40]
Добрый день,
отличная и удобная сборка, но столкнулся с проблемами.

- [ ] 

При очередном запуске **npm run dev** выдаёт серию таких ошибок:

![Снимок экрана 2024-06-20 121645](https://github.com/maxdenaro/gulp-maxgraph/assets/154054760/a732f90b-580b-40cc-82df-f87fad1a6a02)

И далее, по предложенным в терминале инструкциям, создаю в корне проекта файл **webpack.config.js** , и следую этой инструкции, например:

**If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "domain": require.resolve("domain-browser") }'
        - install 'domain-browser'**
     
Но ровным счётом ничего не происходит. Проект запускается, но без JS. Консоль выдаёт ошибки:

![Снимок экрана 2024-06-20 121958](https://github.com/maxdenaro/gulp-maxgraph/assets/154054760/1ace7b13-1665-4b5d-8af1-f232ce3b57fa)

- [ ] 

Создаю новый проект, клонирую ваш репозиторий, устанавливаю зависимости, запускаю **npm run dev**, консоль выдаёт

![Снимок экрана 2024-06-20 120312](https://github.com/maxdenaro/gulp-maxgraph/assets/154054760/238cd387-83ad-4873-9ce1-539019a0b759)

Было бы круто, если бы вы подсказали, как поступить

**Comment by maxdenaro** [comment]
Добрый день. Похоже, будто у вас не самая последняя версия вебпака установлена. Попробуйте установить, для начала)

Ну и на самом деле я мало чем помогу, я ведь просто гуглю ваши ошибки, как могли бы загуглить и вы.
https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5
