### ISSUE TITLE
Нюанс с типографом

### ISSUE THREAD

**Issue by Artem-Golovchansky** [maxdenaro/gulp-maxgraph#41]
Здравствуйте. Собираю сайт на Вашей сборке. Нужно разместить ссылку с номером телефона со скобочками. 
Скобочки сборщик, кажется, обрезает. 
![image](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/22e7fd98-e4e5-49b6-8541-2e10385b4943)
Итог сборки таков: 
![image](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/878b830a-4149-474f-b5ef-a37e9b6734a6)

**Comment by maxdenaro** [comment]
Добрый вечер.
Да, все так. Тут, скорее всего, ничего не сделаешь (разве что отключить полностью Типограф).

**Comment by Artem-Golovchansky** [comment]
> Добрый вечер. Да, все так. Тут, скорее всего, ничего не сделаешь (разве что отключить полностью Типограф).

Не подскажете, как это можно аккуратно сделать, чтобы потом всё остальное работало? :)

![image](https://github.com/maxdenaro/gulp-maxgraph/assets/153385187/645731c4-4ebf-448e-9b1e-9a79f52507b1)

**Comment by maxdenaro** [comment]
![image](https://github.com/maxdenaro/gulp-maxgraph/assets/25548841/b92aa5c6-8598-4fe8-bc4e-b8b077c1fc9b)
Можно просто вот это закомментировать

**Comment by Artem-Golovchansky** [comment]
> ![image](https://private-user-images.githubusercontent.com/25548841/344495609-b92aa5c6-8598-4fe8-bc4e-b8b077c1fc9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODMyNTAsIm5iZiI6MTcxOTc4Mjk1MCwicGF0aCI6Ii8yNTU0ODg0MS8zNDQ0OTU2MDktYjkyYWE1YzYtODU5OC00ZmU4LWJjNGUtYjhiMDc3YzFmYzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIxMjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ODc3MWM5YjQyYzExNjhhNTFkYjQyNjE3YmYxNmU3NTlmYTY2YjJiODY3MjU2YTgwMWIwOGI4ZDRjZDc0YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DS_9In7uk8iks0g2v6rlNOXdQx78yqXl3y0t4iWMWQ8) Можно просто вот это закомментировать.

О! Всё получилось. Благодарю

**Comment by maxdenaro** [comment]
Отлично)
