### ISSUE TITLE
Неправильные окончания строк или отсутствие последней новой строки

### ISSUE THREAD

**Issue by dimadodonov** [maxdenaro/gulp-maxgraph#42]
Привет.

Сегодня скачал сборку, и без какких либо вмещательств решил протестировать, через терминал ввел npm run build, вот что вышло: 

`Выполнение задачи: npm run build 

> gulp-builder@3.0.0 build
> npm run stylelint && npm run code && gulp build --build

> gulp-builder@3.0.0 stylelint
> npx stylelint **/*.scss

> gulp-builder@3.0.0 code
> editorconfig-checker

Downloading v3.0.3
.ecrc:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.editorconfig:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.gitignore:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.htmlhintrc:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.stylelintignore:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.vscode/extensions.json:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
.vscode/snippets/html.json:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/config/paths.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/cache.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/clean.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/html-include.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/html-minify.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/images.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/resources.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/rewrite.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/scripts-backend.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/scripts.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/sprite.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/styles-backend.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/styles.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/webp.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
gulp/tasks/zip.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/index.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/_components.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/_functions.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/_vars.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/components/ex.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/burger.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/check-viewport.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/disable-scroll.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/enable-scroll.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/fix-fullheight.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/header-height.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/mobile-check.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/throttle.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/functions/validate-forms.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/js/main.js:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/partials/footer.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/partials/head.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/partials/header.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/partials/video.html:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/_fonts.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/_mixins.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/_settings.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/_vars.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/components/_header.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/components/_video.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/main.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_breakpoint.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_burger.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_checkbox.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_disable-mob-hover.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_flex.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_font-face.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_layout.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_mini.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character
src/scss/mixins/_tabs.scss:
        Wrong line endings or no final newline
        Not all lines have the correct end of line character

114 errors found`

`
У меня Windows 11

gulp -v
CLI version: 3.0.0
Local version: Unknown

node -v
v20.17.0
`

**Comment by dimadodonov** [comment]
Дубль https://github.com/maxdenaro/gulp-maxgraph/issues/37

**Comment by maxdenaro** [comment]
Привет. Кажется, сборка тут не причём. Скорее всего редактор кода у тебя так обработал файлы, убрал линию в конце.

Тут можно прогуглить ошибку и поправить, либо просто убрать проверку editorconfig из build-сборки

**Comment by dimadodonov** [comment]
> Привет. Кажется, сборка тут не причём. Скорее всего редактор кода у тебя так обработал файлы, убрал линию в конце.
> 
> Тут можно прогуглить ошибку и поправить, либо просто убрать проверку editorconfig из build-сборки 

Да, я думаю это у меня конфиг в prettier неправильно настроен, временно выпилил чекер из build-сборки, спасибо за сборку!

**Comment by maxdenaro** [comment]
Ну отлично)
