### ISSUE TITLE
npm ERR! Build failed with error code: 1

### ISSUE THREAD

**Issue by Endo-Resu** [maxdenaro/gulp-maxgraph#7]
При попытке установить зависимости сборки стабильно вылетает ошибка.
Прикладываю логи с python и без.
Первый лог:
[2021-12-13T19_50_30_926Z-debug-0.log](https://github.com/maxdenaro/gulp-maxgraph/files/7711187/2021-12-13T19_50_30_926Z-debug-0.log)
Второй лог:
[2021-12-14T10_07_13_083Z-debug-0.log](https://github.com/maxdenaro/gulp-maxgraph/files/7711189/2021-12-14T10_07_13_083Z-debug-0.log)

**Comment by maxdenaro** [comment]
Эта ошибка не влияет на установку самих зависимостей же.

**Comment by Endo-Resu** [comment]
> Эта ошибка не влияет на установку самих зависимостей же.

Локальные модули с ней не ставятся, соответственно галп не работает.

**Comment by maxdenaro** [comment]
А какая версия ноды?

**Comment by Endo-Resu** [comment]
node 16.3.1
npm/npx 8.3.0
gulp cli 2.3.0

**Comment by Endo-Resu** [comment]
Смог починить у себя, сделал пулриквест, ознакомься.
Я думаю его стоит отклонить, но где-то записать, что делать в случае моей ошибки)

**Comment by maxdenaro** [comment]
Что-то не вижу пулл реквеста)

**Comment by Endo-Resu** [comment]
А сейчас?
Сорьки, только начинаю работать с гитом, так что тупнячков ловлю много)
