### ISSUE TITLE
папка parts

### ISSUE THREAD

**Issue by drDramen** [maxdenaro/gulp-maxgraph#8]
"а вот html (и js, если нужен) код к ним написан в соответствующих файлах в папке parts. "

не нашел такой папки в проекте.

**Comment by maxdenaro** [comment]
Привет! Я ее убрал уже давненько, не обновил readme

**Comment by drDramen** [comment]
Привет. Понял. Только вот scss остался.

**Comment by maxdenaro** [comment]
Да, он и должен был остаться)
